[package]
name = "db"
version = "0.1.0"
description = "Internal data structures for the Japanese dictionary"
keywords = ["japanese"]
publish = false

[dependencies]
unicode-segmentation = "1.6"
