[package]
name = "query"
version = "0.1.0"
authors = ["Ricardo B. Machado <ricardobm@gmail.com>"]
license = "MIT"
description = "Query client for jp-dict"
publish = false

[dependencies]
jp-dict = { path = "../../" }
rustyline = "6.0"

[features]
no-embed = ["jp-dict/no-embed"]
