[package]
name = "query"
version = "0.1.0"
authors = ["Ricardo B. Machado <ricardobm@gmail.com>"]
license = "MIT"
description = "Query client for x-jp-data"
publish = false

[dependencies]
x-jp-data = { path = "../../" }
rustyline = "6.0"

[features]
no-embed = ["x-jp-data/no-embed"]
