[package]
name = "query"
version = "0.1.0"
authors = ["Ricardo B. Machado <ricardobm@gmail.com>"]
license = "MIT"
description = "Query client for x-jisho-data"
publish = false

[dependencies]
x-jisho-data = { path = "../../" }
